import { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

type Props = { ownersList: Owner[] };

const Home: NextPage<Props> = ({ ownersList }) => {
    // const [owners, setOwners] = useState<Owner[]>([]);

    // useEffect(() => {
    //     async function loadData() {
    //         const response = await fetch("http://localhost:4001/vehicles");
    //         const data = await response.json();
    //         setOwners(data);
    //     }
    //     loadData();
    // }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {ownersList.map((owner) => (
                <ul key={owner.id}>
                    <li>
                        <Link
                            as={`/${owner.vehicle}/${owner.ownerName}`}
                            href="/[vehicle]/[person]"
                        >
                            Navigate to {owner.ownerName}&apos;s {owner.vehicle}
                        </Link>
                    </li>
                </ul>
            ))}
        </div>
    );
};

export default Home;

Home.getInitialProps = async () => {
    const response = await fetch("http://localhost:4001/vehicles");
    const data = await response.json();
    return {
        ownersList: data,
    };
};
